### PR TITLE
Update index.html to use https

### PR DESCRIPTION
**Pull request by volkflo**
Change resources to https so that chrome does not complain anymore.

### CODE REVIEW

**Comment by volkflo** [comment]
After merging this we should enforce https on the website: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Review by EricWittmann — APPROVED** [review]
+1

**Comment by EricWittmann** [comment]
Done and done.

**Comment by volkflo** [comment]
Great, thanks :)

**Comment by volkflo** [comment]
Unfortunately, this not all links use https, so the CSS of the blog is broken now. We will fix this with the update of the website for the developer portal :)

**Pull request merged**
