### PR TITLE
Add support for asciidoc(tor) formatted blogs, including styling for admonitions

### PR DESCRIPTION
**Pull request by msavy**
This took me a (very) surprisingly long time to work out, with some undocumented settings used to get it working. This way means that generated images are put in the correct locations during generation, with the correct path put into the HTML for when it's loaded in the browser. 

You may need to do:
    - gem install asciidoctor
    - gem install asciidoctor-diagram --pre

I spent a while chopping up the asciidoctor sass to make some admonition styles that fit with our styles. I didn't want to do anything too outlandish without consulting first, so it's basic. I have some ideas, though, so we should chat about that at some point.

Here's an example of what it looks like:

screen shot 2015-06-07 at 17 39 14

### CODE REVIEW

**Comment by EricWittmann** [comment]
This can't be merged.  Can you resolve conflicts and update the PR?

**Comment by msavy** [comment]
Okay, redone. Please have a play around and see if everything looks good. BTW - I will need to rebase my blogposts, but that shouldn't be too hard with this done.

**Comment by EricWittmann** [comment]
Still can't be automatically merged.

**Comment by msavy** [comment]
whoops!

**Pull request merged**
