### PR TITLE
Blogpost For Review: CORS, Of Course! 

### PR DESCRIPTION
**Pull request by msavy**
Planned merge: 2015-07-01 15:00:00 +0100

### CODE REVIEW

**Comment by EricWittmann** [comment]
Looks good to me - did you want to wait until July 1 to post it?

**Comment by msavy** [comment]
Yeah, was thinking about 1st July for posting this. I reckon it's good to space our content out a bit, rather than splurging it all in one go!

**Comment by EricWittmann** [comment]
OK - when the time comes let me know, otherwise I'll forget. :)  Also - you'll need to rebase at that time.

**Comment by msavy** [comment]
See instead https://github.com/apiman/apiman.github.io/pull/18

**Pull request closed without merging**
