### PR TITLE
Cors blogpost 2 (merge at midday)

### PR DESCRIPTION
**Pull request by msavy**

### CODE REVIEW

**Comment by msavy** [comment]
What do you think about having each blogpost title in the RSS prepended with "Apiman: <title>". Just thinking that sometimes it's unclear what the title refers to in the syndicated feeds sometimes. IMO that's more of a problem with the syndication being unclear as to its source.

**Comment by EricWittmann** [comment]
Looking at planet.jboss.org, all of the apiman posts have "In apiman" in the meta-data (below the author).  I think that's fine.

**Comment by msavy** [comment]
I was thinking mainly for the jboss.org frontpage, but it doesn't matter so much now I think of it.

**Comment by EricWittmann** [comment]
Oh cool - I didn't even know they syndicated there. :)

**Pull request merged**
